DEFAULT_CONFLICT_PENALTY = -100
DEFAULT_BEFORE_9_PENALTY = -10
DEFAULT_AFTER_17_PENALTY = -10
DEFAULT_OVER_2_WINDOW_PENALTY = -10

DEFAULT_FREE_DAY_BONUS = 20
DEFAULT_NOT_BEFORE_11_BONUS = 10
DEFAULT_NOT_AFTER_15_BONUS = 10

def rate_chromosome(self):
    """
    """
    pass
